### PR TITLE
Allow whitelisting entire domains

### PR DESCRIPTION
**Pull request by gavinwahl**

### CODE REVIEW

**Comment by gavinwahl** [comment]
Is this project still maintained? Should I release a fork?

**Comment by mlavin** [comment]
This project is maintained for changes related to Django/Python support but we don't have any major feature development planned. You are of course welcome to release your own fork under the terms of this project's license. If you would like this change merged here then this should have a test.

**Comment by gavinwahl** [comment]
Added a test.

**Comment by mlavin** [comment]
Looks good to me. Thank you! :heart_eyes:

**Comment by gavinwahl** [comment]
When is the next release of django-email-bandit planned?

**Pull request merged**
